# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83174bef1d91ce4fbbb9d25b98be1d1775320950db9dc2449443493fa1d8683bb842270ec5aa7d4d840108d18a9e5fafabbe9dde1bbc461ef73e069304e5aad7

test:
  secret_key_base: 13693083ecf815c735a0ed61597de89e52a67f2cf84d79e5a976e123d9f4e575d17c65a2d3de59f9e7b8d48e2f73a6f7139a2fb3d9f0f29681bb7e3e812ff22e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
